const NEXT_PUBLIC_WORDPRESS_GRAPHQL_URL =
  process.env.NEXT_PUBLIC_WORDPRESS_GRAPHQL_URL;
if (!NEXT_PUBLIC_WORDPRESS_GRAPHQL_URL) {
  throw new Error("NEXT_PUBLIC_WORDPRESS_GRAPHQL_URL is missing in .env");
}

const NEXT_PUBLIC_WORDPRESS_API_URL = process.env.NEXT_PUBLIC_WORDPRESS_API_URL;
if (!NEXT_PUBLIC_WORDPRESS_API_URL) {
  throw new Error("NEXT_PUBLIC_WORDPRESS_API_URL is missing in .env");
}

export const env = {
  NEXT_PUBLIC_WORDPRESS_GRAPHQL_URL,
  NEXT_PUBLIC_WORDPRESS_API_URL,
};
