/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "query GetKnowledgeArticle($slug: ID!) {\n  knowledgeArticle(id: $slug, idType: SLUG) {\n    id\n    databaseId\n    title\n    date\n    slug\n    content\n    excerpt\n    featuredImage {\n      node {\n        sourceUrl\n        altText\n      }\n    }\n    knowledgeArticleFields {\n      readingTime\n      author {\n        nodes {\n          ... on Author {\n            title\n            authorFields {\n              role\n              avatar {\n                node {\n                  sourceUrl\n                  altText\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n    knowledgeCategories {\n      nodes {\n        name\n        slug\n      }\n    }\n    views\n  }\n}": typeof types.GetKnowledgeArticleDocument,
    "query GetKnowledgeArticles($first: Int = 10) {\n  knowledgeArticles(first: $first) {\n    nodes {\n      id\n      databaseId\n      title\n      date\n      slug\n      excerpt\n      featuredImage {\n        node {\n          sourceUrl\n          altText\n        }\n      }\n      knowledgeArticleFields {\n        readingTime\n        author {\n          nodes {\n            ... on Author {\n              title\n              authorFields {\n                role\n                avatar {\n                  node {\n                    sourceUrl\n                    altText\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n      knowledgeCategories {\n        nodes {\n          name\n          slug\n        }\n      }\n      views\n    }\n  }\n}": typeof types.GetKnowledgeArticlesDocument,
    "query GetKnowledgeArticlesByIds($ids: [ID]) {\n  knowledgeArticles(where: {in: $ids}) {\n    nodes {\n      id\n      databaseId\n      title\n      date\n      slug\n      excerpt\n      featuredImage {\n        node {\n          sourceUrl\n          altText\n        }\n      }\n      knowledgeArticleFields {\n        readingTime\n        author {\n          nodes {\n            ... on Author {\n              title\n              authorFields {\n                role\n                avatar {\n                  node {\n                    sourceUrl\n                    altText\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n      knowledgeCategories {\n        nodes {\n          name\n          slug\n        }\n      }\n      views\n    }\n  }\n}": typeof types.GetKnowledgeArticlesByIdsDocument,
    "query GetKnowledgeArticlesCount {\n  knowledgeArticlesCount\n}": typeof types.GetKnowledgeArticlesCountDocument,
    "query GetKnowledgeArticlesPaginated($first: Int!, $after: String) {\n  knowledgeArticles(first: $first, after: $after) {\n    nodes {\n      id\n      databaseId\n      title\n      date\n      slug\n      excerpt\n      featuredImage {\n        node {\n          sourceUrl\n          altText\n        }\n      }\n      knowledgeArticleFields {\n        readingTime\n        author {\n          nodes {\n            ... on Author {\n              title\n              authorFields {\n                role\n                avatar {\n                  node {\n                    sourceUrl\n                    altText\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n      knowledgeCategories {\n        nodes {\n          name\n          slug\n        }\n      }\n      views\n    }\n    pageInfo {\n      hasNextPage\n      endCursor\n    }\n  }\n}": typeof types.GetKnowledgeArticlesPaginatedDocument,
    "query GetPopularKnowledgeArticleIds {\n  popularKnowledgeArticles\n}": typeof types.GetPopularKnowledgeArticleIdsDocument,
    "query GetRelatedKnowledgeArticles($categorySlugs: [String!], $excludeIds: [ID!], $first: Int = 5) {\n  knowledgeCategories(where: {slug: $categorySlugs}) {\n    nodes {\n      knowledgeArticles(first: $first, where: {notIn: $excludeIds}) {\n        nodes {\n          id\n          databaseId\n          title\n          date\n          slug\n          excerpt\n          featuredImage {\n            node {\n              sourceUrl\n              altText\n            }\n          }\n          knowledgeArticleFields {\n            readingTime\n            author {\n              nodes {\n                ... on Author {\n                  title\n                  authorFields {\n                    role\n                    avatar {\n                      node {\n                        sourceUrl\n                        altText\n                      }\n                    }\n                  }\n                }\n              }\n            }\n          }\n          knowledgeCategories {\n            nodes {\n              name\n              slug\n            }\n          }\n          views\n        }\n      }\n    }\n  }\n}": typeof types.GetRelatedKnowledgeArticlesDocument,
};
const documents: Documents = {
    "query GetKnowledgeArticle($slug: ID!) {\n  knowledgeArticle(id: $slug, idType: SLUG) {\n    id\n    databaseId\n    title\n    date\n    slug\n    content\n    excerpt\n    featuredImage {\n      node {\n        sourceUrl\n        altText\n      }\n    }\n    knowledgeArticleFields {\n      readingTime\n      author {\n        nodes {\n          ... on Author {\n            title\n            authorFields {\n              role\n              avatar {\n                node {\n                  sourceUrl\n                  altText\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n    knowledgeCategories {\n      nodes {\n        name\n        slug\n      }\n    }\n    views\n  }\n}": types.GetKnowledgeArticleDocument,
    "query GetKnowledgeArticles($first: Int = 10) {\n  knowledgeArticles(first: $first) {\n    nodes {\n      id\n      databaseId\n      title\n      date\n      slug\n      excerpt\n      featuredImage {\n        node {\n          sourceUrl\n          altText\n        }\n      }\n      knowledgeArticleFields {\n        readingTime\n        author {\n          nodes {\n            ... on Author {\n              title\n              authorFields {\n                role\n                avatar {\n                  node {\n                    sourceUrl\n                    altText\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n      knowledgeCategories {\n        nodes {\n          name\n          slug\n        }\n      }\n      views\n    }\n  }\n}": types.GetKnowledgeArticlesDocument,
    "query GetKnowledgeArticlesByIds($ids: [ID]) {\n  knowledgeArticles(where: {in: $ids}) {\n    nodes {\n      id\n      databaseId\n      title\n      date\n      slug\n      excerpt\n      featuredImage {\n        node {\n          sourceUrl\n          altText\n        }\n      }\n      knowledgeArticleFields {\n        readingTime\n        author {\n          nodes {\n            ... on Author {\n              title\n              authorFields {\n                role\n                avatar {\n                  node {\n                    sourceUrl\n                    altText\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n      knowledgeCategories {\n        nodes {\n          name\n          slug\n        }\n      }\n      views\n    }\n  }\n}": types.GetKnowledgeArticlesByIdsDocument,
    "query GetKnowledgeArticlesCount {\n  knowledgeArticlesCount\n}": types.GetKnowledgeArticlesCountDocument,
    "query GetKnowledgeArticlesPaginated($first: Int!, $after: String) {\n  knowledgeArticles(first: $first, after: $after) {\n    nodes {\n      id\n      databaseId\n      title\n      date\n      slug\n      excerpt\n      featuredImage {\n        node {\n          sourceUrl\n          altText\n        }\n      }\n      knowledgeArticleFields {\n        readingTime\n        author {\n          nodes {\n            ... on Author {\n              title\n              authorFields {\n                role\n                avatar {\n                  node {\n                    sourceUrl\n                    altText\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n      knowledgeCategories {\n        nodes {\n          name\n          slug\n        }\n      }\n      views\n    }\n    pageInfo {\n      hasNextPage\n      endCursor\n    }\n  }\n}": types.GetKnowledgeArticlesPaginatedDocument,
    "query GetPopularKnowledgeArticleIds {\n  popularKnowledgeArticles\n}": types.GetPopularKnowledgeArticleIdsDocument,
    "query GetRelatedKnowledgeArticles($categorySlugs: [String!], $excludeIds: [ID!], $first: Int = 5) {\n  knowledgeCategories(where: {slug: $categorySlugs}) {\n    nodes {\n      knowledgeArticles(first: $first, where: {notIn: $excludeIds}) {\n        nodes {\n          id\n          databaseId\n          title\n          date\n          slug\n          excerpt\n          featuredImage {\n            node {\n              sourceUrl\n              altText\n            }\n          }\n          knowledgeArticleFields {\n            readingTime\n            author {\n              nodes {\n                ... on Author {\n                  title\n                  authorFields {\n                    role\n                    avatar {\n                      node {\n                        sourceUrl\n                        altText\n                      }\n                    }\n                  }\n                }\n              }\n            }\n          }\n          knowledgeCategories {\n            nodes {\n              name\n              slug\n            }\n          }\n          views\n        }\n      }\n    }\n  }\n}": types.GetRelatedKnowledgeArticlesDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query GetKnowledgeArticle($slug: ID!) {\n  knowledgeArticle(id: $slug, idType: SLUG) {\n    id\n    databaseId\n    title\n    date\n    slug\n    content\n    excerpt\n    featuredImage {\n      node {\n        sourceUrl\n        altText\n      }\n    }\n    knowledgeArticleFields {\n      readingTime\n      author {\n        nodes {\n          ... on Author {\n            title\n            authorFields {\n              role\n              avatar {\n                node {\n                  sourceUrl\n                  altText\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n    knowledgeCategories {\n      nodes {\n        name\n        slug\n      }\n    }\n    views\n  }\n}"): (typeof documents)["query GetKnowledgeArticle($slug: ID!) {\n  knowledgeArticle(id: $slug, idType: SLUG) {\n    id\n    databaseId\n    title\n    date\n    slug\n    content\n    excerpt\n    featuredImage {\n      node {\n        sourceUrl\n        altText\n      }\n    }\n    knowledgeArticleFields {\n      readingTime\n      author {\n        nodes {\n          ... on Author {\n            title\n            authorFields {\n              role\n              avatar {\n                node {\n                  sourceUrl\n                  altText\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n    knowledgeCategories {\n      nodes {\n        name\n        slug\n      }\n    }\n    views\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query GetKnowledgeArticles($first: Int = 10) {\n  knowledgeArticles(first: $first) {\n    nodes {\n      id\n      databaseId\n      title\n      date\n      slug\n      excerpt\n      featuredImage {\n        node {\n          sourceUrl\n          altText\n        }\n      }\n      knowledgeArticleFields {\n        readingTime\n        author {\n          nodes {\n            ... on Author {\n              title\n              authorFields {\n                role\n                avatar {\n                  node {\n                    sourceUrl\n                    altText\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n      knowledgeCategories {\n        nodes {\n          name\n          slug\n        }\n      }\n      views\n    }\n  }\n}"): (typeof documents)["query GetKnowledgeArticles($first: Int = 10) {\n  knowledgeArticles(first: $first) {\n    nodes {\n      id\n      databaseId\n      title\n      date\n      slug\n      excerpt\n      featuredImage {\n        node {\n          sourceUrl\n          altText\n        }\n      }\n      knowledgeArticleFields {\n        readingTime\n        author {\n          nodes {\n            ... on Author {\n              title\n              authorFields {\n                role\n                avatar {\n                  node {\n                    sourceUrl\n                    altText\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n      knowledgeCategories {\n        nodes {\n          name\n          slug\n        }\n      }\n      views\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query GetKnowledgeArticlesByIds($ids: [ID]) {\n  knowledgeArticles(where: {in: $ids}) {\n    nodes {\n      id\n      databaseId\n      title\n      date\n      slug\n      excerpt\n      featuredImage {\n        node {\n          sourceUrl\n          altText\n        }\n      }\n      knowledgeArticleFields {\n        readingTime\n        author {\n          nodes {\n            ... on Author {\n              title\n              authorFields {\n                role\n                avatar {\n                  node {\n                    sourceUrl\n                    altText\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n      knowledgeCategories {\n        nodes {\n          name\n          slug\n        }\n      }\n      views\n    }\n  }\n}"): (typeof documents)["query GetKnowledgeArticlesByIds($ids: [ID]) {\n  knowledgeArticles(where: {in: $ids}) {\n    nodes {\n      id\n      databaseId\n      title\n      date\n      slug\n      excerpt\n      featuredImage {\n        node {\n          sourceUrl\n          altText\n        }\n      }\n      knowledgeArticleFields {\n        readingTime\n        author {\n          nodes {\n            ... on Author {\n              title\n              authorFields {\n                role\n                avatar {\n                  node {\n                    sourceUrl\n                    altText\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n      knowledgeCategories {\n        nodes {\n          name\n          slug\n        }\n      }\n      views\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query GetKnowledgeArticlesCount {\n  knowledgeArticlesCount\n}"): (typeof documents)["query GetKnowledgeArticlesCount {\n  knowledgeArticlesCount\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query GetKnowledgeArticlesPaginated($first: Int!, $after: String) {\n  knowledgeArticles(first: $first, after: $after) {\n    nodes {\n      id\n      databaseId\n      title\n      date\n      slug\n      excerpt\n      featuredImage {\n        node {\n          sourceUrl\n          altText\n        }\n      }\n      knowledgeArticleFields {\n        readingTime\n        author {\n          nodes {\n            ... on Author {\n              title\n              authorFields {\n                role\n                avatar {\n                  node {\n                    sourceUrl\n                    altText\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n      knowledgeCategories {\n        nodes {\n          name\n          slug\n        }\n      }\n      views\n    }\n    pageInfo {\n      hasNextPage\n      endCursor\n    }\n  }\n}"): (typeof documents)["query GetKnowledgeArticlesPaginated($first: Int!, $after: String) {\n  knowledgeArticles(first: $first, after: $after) {\n    nodes {\n      id\n      databaseId\n      title\n      date\n      slug\n      excerpt\n      featuredImage {\n        node {\n          sourceUrl\n          altText\n        }\n      }\n      knowledgeArticleFields {\n        readingTime\n        author {\n          nodes {\n            ... on Author {\n              title\n              authorFields {\n                role\n                avatar {\n                  node {\n                    sourceUrl\n                    altText\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n      knowledgeCategories {\n        nodes {\n          name\n          slug\n        }\n      }\n      views\n    }\n    pageInfo {\n      hasNextPage\n      endCursor\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query GetPopularKnowledgeArticleIds {\n  popularKnowledgeArticles\n}"): (typeof documents)["query GetPopularKnowledgeArticleIds {\n  popularKnowledgeArticles\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query GetRelatedKnowledgeArticles($categorySlugs: [String!], $excludeIds: [ID!], $first: Int = 5) {\n  knowledgeCategories(where: {slug: $categorySlugs}) {\n    nodes {\n      knowledgeArticles(first: $first, where: {notIn: $excludeIds}) {\n        nodes {\n          id\n          databaseId\n          title\n          date\n          slug\n          excerpt\n          featuredImage {\n            node {\n              sourceUrl\n              altText\n            }\n          }\n          knowledgeArticleFields {\n            readingTime\n            author {\n              nodes {\n                ... on Author {\n                  title\n                  authorFields {\n                    role\n                    avatar {\n                      node {\n                        sourceUrl\n                        altText\n                      }\n                    }\n                  }\n                }\n              }\n            }\n          }\n          knowledgeCategories {\n            nodes {\n              name\n              slug\n            }\n          }\n          views\n        }\n      }\n    }\n  }\n}"): (typeof documents)["query GetRelatedKnowledgeArticles($categorySlugs: [String!], $excludeIds: [ID!], $first: Int = 5) {\n  knowledgeCategories(where: {slug: $categorySlugs}) {\n    nodes {\n      knowledgeArticles(first: $first, where: {notIn: $excludeIds}) {\n        nodes {\n          id\n          databaseId\n          title\n          date\n          slug\n          excerpt\n          featuredImage {\n            node {\n              sourceUrl\n              altText\n            }\n          }\n          knowledgeArticleFields {\n            readingTime\n            author {\n              nodes {\n                ... on Author {\n                  title\n                  authorFields {\n                    role\n                    avatar {\n                      node {\n                        sourceUrl\n                        altText\n                      }\n                    }\n                  }\n                }\n              }\n            }\n          }\n          knowledgeCategories {\n            nodes {\n              name\n              slug\n            }\n          }\n          views\n        }\n      }\n    }\n  }\n}"];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;